config/routes.rb
Rails.application.routes.draw do
  root 'subs#index'
  resources :subs do
    resources :topics
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sub.rb
class Sub < ApplicationRecord
  has_many :topics, dependent: :destroy
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :sub
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :set_sub, only: [:show, :update, :edit, :destroy]

  def index
    @subs = Sub.all
  end

  def show

  end

  def new
    @sub = Sub.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @sub = Sub.new(sub_params)

    if @sub.save
      redirect_to sub_path(@sub)
    else
      render partial: "form"
    end
  end

  def update
    if @sub.update(sub_params)
      redirect_to sub_path(@sub)
    else
      render partial: "form"
    end
  end

  def destroy
    @sub.destroy
    redirect_to subs_path
  end

  private

    def set_sub
      @sub = Sub.find(params[:id])
    end

    def sub_params
      params.require(:sub).permit(:name)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/_form.html.erb
<h1><%= @sub.id ? 'Edit Sub' : 'Create Sub' %></h1>
<hr>
<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
<% end %>

app/views/subs/index.html.erb
<h1>Click a Sub to View</h1>
<%= link_to 'Create A New Sub', new_sub_path %>
<ul>
  <% @subs.each do |sub| %>
    <li>
    <%= link_to sub.name, sub %>
    </li>
  <% end %>
</ul>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>
<hr>
<p>What would you like to do?</p>
<%= link_to 'View Topics', sub_topics_path(@sub) %>
<br>
<%= link_to 'Edit Sub', edit_sub_path(@sub) %>
<br>
<%= link_to 'Delete Sub', @sub, method: :delete %>
<br>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Topics#index</h1>
<p>Find me in app/views/topics/index.html.erb</p>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1>Topics#show</h1>
<p>Find me in app/views/topics/show.html.erb</p>